version: "3"

services:

  # wsgi
  backend:
      build: .
      command: python src/manage.py runserver 0:8000
      # command: tail -F /dev/null
      container_name: backend
      restart: always
      volumes:
        - "./:/srv/project"
      depends_on:
        - rabbitmq
        - postgres
        - memcached
      ports:
        - "8000:8000"

  celery:
      build: .
      command: /bin/bash ./commands/start_celery.sh
      container_name: celery
      restart: always
      depends_on:
        - rabbitmq
        - postgres
      volumes:
        - ./:/srv/project

  celerybeat:
      build: .
      command: celery -A currency_exchange beat -l info --workdir=/srv/project/src
      container_name: celerybeat
      restart: always
      depends_on:
        - rabbitmq
        - postgres
      volumes:
        - ./:/srv/project

  rabbitmq:
      image: rabbitmq:3.8-rc-management
      container_name: rabbitmq
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"

  memcached:
      image: memcached:latest
      container_name: memcached
      restart: always
      ports:
        - "11211:11211"

  postgres:
      image: postgres:11.3
      container_name: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=123456qwerty
        - POSTGRES_USER=ce
        - POSTGRES_DB=currency_exchange
#        - POSTGRES_PORT: 5432
      volumes:
        - pgdata:/var/lib/postgresql/data

  nginx:
      image: nginx:1.17.4-alpine
      #build: ./nginx
      container_name: nginx
      volumes:
        - ./nginx:/etc/nginx/conf.d/
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - backend

volumes:
  pgdata: