# Generated by Django 2.2.10 on 2020-03-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20200220_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'Monobank'), (3, 'Vkurse'), (4, 'Pumb')]),
        ),
    ]
